```{mermaid}
timeline
    title Nascita e sviluppo del linguaggio C
    1972 : nasce C (New B) presso i Bell Labs.
    1973 : UNIX viene interamente riscritto in C.
    1978 : Kerninghan & Ritchie pubblicano The C Programming Language.
    1989 : Primo Standard C (ISO C89)
    1999 : Secondo standard C (ISO C99)
```