timeline
    section Birth of C
        1972 : nasce C (New B) presso i Bell Labs.
        1973 : UNIX viene interamente riscritto in C.
    section Definition of C Language
        1978 : Kerninghan & Ritchie pubblicano The C Programming Language.
        1989 : Primo Standard C (C89)
    section Actual C
        1999 : Secondo standard C (C99)
        2011 : Terzo standard C (C11)
