project:
  type: website

website:
  title: "Hello C 2024"
  favicon: assets/images/dec_pdp1120.png
  page-navigation: true
  bread-crumbs: true
  description: Questo libro è un'introduzione al linguaggio di programmazione C. Attualmente è in fase di sviluppo e non è ancora completo.
  repo-url: https://github.com/matteospanio/corso-c
  repo-branch: master
  repo-actions: [issue]
  search:
    type: overlay
    show-item-context: tree
  reader-mode: true
  comments:
    hypothesis:
      theme: clean
      openSidebar: false

  navbar:
    background: "#9b0014"
    logo: assets/images/dec_pdp1120.png
    logo-alt: Hello C
    collapse-below: lg

    left:
      - text: Lezioni
        href: lessons.qmd
      - text: Esercizi
        href: exercises.qmd
      - text: Risorse
        href: resources.qmd

    tools:
      - icon: github
        href: https://github.com/matteospanio/corso-c
        text: GitHub

  page-footer:
    left: "© 2024, Matteo Spanio"
    center:
      - text: "FAQ"
        href:  faq.qmd
      - text: "Forum"
        href: https://stem.elearning.unipd.it/mod/forum/view.php?id=470278
      - text: "Licenza"
        href:  extra/license.qmd
    right:
      - icon: github
        href: https://github.com/matteospanio/corso-c
        aria-label: Github Hello C

  sidebar:
    - id: lessons
      title: Lezioni
      contents:
        - lessons/01/index.qmd
        - lessons/02/index.qmd
        - lessons/03/index.qmd
        - lessons/04/index.qmd
        - lessons/05/index.qmd
        - lessons/06/index.qmd

    - id: exercises
      title: Esercizi
      contents:
        - section: Basi di C
          contents:
            - href: exercises/01/somma_interi.qmd
              text: Somma di interi
            - href: exercises/01/somma_razionale.qmd
              text: Somma razionale
            - href: exercises/01/cambio_valuta.qmd
              text: Cambio valuta
            - href: exercises/01/libretto.qmd
              text: Libretto universitario
        - section: Espressioni e strutture di controllo
          contents:
            - href: exercises/02/power.qmd
              text: Elevamento a potenza
            - href: exercises/02/lista_della_spesa.qmd
              text: Lista della spesa
            - href: exercises/02/fizzbuzz.qmd
              text: FizzBuzz
        - section: Array e funzioni
          contents:
            - href: exercises/02/sum_matrix.qmd
              text: Somma di righe e colonne
            - href: exercises/02/word_average.qmd
              text: Lunghezza media delle parole
            - href: exercises/02/deal.qmd
              text: Una mano a poker

    - id: resources
      title: Risorse
      contents:
        - href: resources.qmd
          section: Risorse
          contents:
          - href: extra/books.qmd
            text: Libri di testo
          - href: extra/docker.qmd
            text: Ambiente di sviluppo
        - section: Strumenti di sviluppo
          contents:
          - href: extra/gcc.qmd
            text: Il compilatore GCC
          - href: extra/makefile.qmd
            text: Automatizzare la compilazione
          - href: extra/gdb.qmd
            text: Usare il debugger GDB
        - section: Come scrivere codice
          contents:
          - href: extra/style_guide.qmd
            text: Style Guide
          - href: extra/formatting.qmd
            text: Formatting
        - href: faq.qmd

format:
  html:
    lang: it
    theme:
      light: cosmo
      dark: darkly
    code-copy: true
    toc: true

bibliography: references.bib
