## Tipi di dato

Le varibili possono contenere diversi tipi di dati, i tipi di dati base in C sono:

- interi: int, short, long int, unsigned short/int/long int
- virgola mobile: float, double, long double
- char: caratteri

Inoltre esiste il tipo speciale `void` che indica l'assenza di informazione.

## Tipi numerici

I vari tipi di interi e tipi di virgola mobile si distinguono per il numero di byte usati per la loro rappresentazione in memoria e, conseguentemente, per il range di valori che possono rappresentare.

::: {.callout-note}
Il numero di byte usati per rappresentare un tipo di dato dipende dal compilatore e dall'architettura del computer. Per sapere quanti byte vengono usati per rappresentare un tipo di dato si può usare l'operatore `sizeof`.

Per conoscere il range di valori che può rappresentare un tipo di dato si può usare la libreria `limits.h` per i tipi interi e `float.h` per i tipi di virgola mobile.
:::

## Tipi numerici

```{.c}
{{< include ./code/limits.c >}}
```

::: {.aside}
Quando si ha a che fare con questi valori è bene stare attenti agli overflow.
:::

## Tipi char

Il tipo `char` è usato per rappresentare un singolo carattere. In C i caratteri sono rappresentati come interi senza segno di 8 bit.

I char vanno sempre scritti tra apici singoli, scrivendo un solo carattere. Il C lin interpreterà come un intero.

## Conversioni tra tipi

In generale, per effettuare operazioni aritmetiche tra due numeri, questi devono essere dello stesso tipo.

In C è possibile mescolare tipi diversi nella stessa espressione, e il compilatore effettuerà automaticamente le conversioni necessarie per eseguire l'operazione richiesta.

## Conversioni implicite

```{.c}
int a = 5;
float b = 1.618;

a + b; // 6.618
```

In questo esempio, il valore intero a viene convertito implicitamente in virgola mobile prima di eseguire l'operazione di somma. Questo tipo di conversione è chiamato "*promotion*".

## Conversioni implicite

Se assegno un valore a una variabile di tipo diverso, il compilatore effettuerà una conversione implicita.

```{.c}
int i = 1;
float f;
f = i; // 1.0
f = 2; // 2.0
```

È vero quindi anche il contrario:

```{.c}
float f = 1.618;
int i;
i = f; // 1
```

## Cast espliciti

È possibile convertire esplicitamente il tipo di un' espressione con l'operazione di casting:

`(nome_tipo) espressione`

Il risultato dell'espressione viene convertito al tipo specificato.

Un caso frequente è quando si esegue una divisione tra due interi:

```{.c}
float quotient;
int dividend, divisor;
quotient = (float) dividend / divisor;
```
