---
title: "Esercizio: il libretto degli esami"
---

Si vuole scrivere un programma che, dati in input i voti di più esami e i relativi crediti, calcoli la media ponderata dei voti e la visualizzi a video.

::: {.callout-note appearance="minimal"}
Si assume che gli esami siano 3: algebra lineare, analisi matematica e introduzione alla programmazione (java).
:::

Quando il programma viene eseguito deve chiedere all'utente di inserire il voto di un certo esame e il relativo numero di crediti associato. Una volta inseriti tutti i voti e i crediti, il programma deve calcolare la media ponderata e visualizzarla a video.

**Opzionale**:

- Provare a visualizzare anche la media aritmetica dei voti;
- Visualizzare anche l'elenco dei voti e dei crediti inseriti.
- Prova a stampare il voto con 2 cifre decimali, ad esempio `27.11` (per fare questo bisogna cambiare il tipo di dato usato per memorizzare la media e usare il *type casting* durante la divisione).

::: {.callout-tip}
## Suggerimento
La media ponderata si calcola come la somma dei prodotti tra ciascun voto e i relativi crediti, diviso la somma dei crediti. Formalmente:

$$
\text{media} = \frac{\sum_{i=1}^{n} voto_i \cdot crediti_i}{\sum_{i=1}^{n} crediti_i}
$$
dove $voto_i$ è il voto dell'esame $i$-esimo e $crediti_i$ è il numero di crediti dell'esame $i$-esimo.

Ad esempio, se si hanno tre esami con voti 30, 28 e 25 e i rispettivi crediti sono 6, 9 e 12, la media ponderata è:
$$
\frac{30 \cdot 6 + 28 \cdot 9 + 25 \cdot 12}{6 + 9 + 12} = \frac{180 + 252 + 300}{27} = \frac{732}{27} \approx 27.11
$$
:::

Esempio di main:

:::{.aside}
{{< downloadthis ./code/libretto.c dname="libretto" label="Scarica il file" >}}
:::
```{.c}
{{< include ./code/libretto.c >}}
```

<!-- ::: {.callout-tip collapse="true"}
## Soluzione

```{.c}
{{< include ./code/libretto.c >}}
```

::: -->
