---
title: "Esercizio: somma di interi"
---

Si vuole scrivere un programma che accetti in input due numeri interi e ne calcoli la somma. Il programma deve chiedere all'utente di inserire i due numeri, effettuare il calcolo e visualizzare il risultato a video.

Ad esempio:
```{.raw}
Inserisci il primo numero: 5
Inserisci il secondo numero: 7
La somma dei due numeri è 12
```

Una volta compilato il programma eseguilo con `gdb` e controlla il valore delle variabili prima e dopo l'assegnamento. Cosa noti?

::: {.callout-tip}
## GNU Debugger

Per eseguire un programma con `gdb` è sufficiente digitare il comando `gdb nome_programma` da terminale. Una volta avviato il debugger è possibile aggiungere breakpoints con il comando `break nome_funzione` o `break numero_riga`. A questo punto è possibile eseguire il programma con il comando `run` e controllare il valore delle variabili con il comando `print nome_variabile`. Per andare avanti di un passo è possibile usare il comando `next` o `step`. Per uscire dal debugger è sufficiente digitare `quit`.
:::

::: {.callout-tip collapse="true"}
## Soluzione

```{.c}
{{< include ./code/sum.c >}}
```

:::
